name: Sync Image to Aliyun Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Aliyun Registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKER_USERNAME }}" --password-stdin registry.cn-hangzhou.aliyuncs.com
												   
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo copy docker://docker.io/gitlab/gitlab-ce:10.6.2-ce.0 docker://registry.cn-hangzhou.aliyuncs.com/anle_repo/gitlab/gitlab-ce:10.6.2-ce.0
